# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "ryttge"
chip = "esp32s3"
usb_enable = true

[matrix]
# Input and output pins are mandatory
input_pins = ["GPIO6"]
output_pins = ["GPIO7"]

#matrix_type = "direct_pin"
#direct_pins = [
#    ["GPIO6"],
#    ["GPIO7"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
#]

[layout]
rows = 1
cols = 1
layers = 1
matrix_map = """
(0,0)
"""
# layer 0 (default):
[[layer]]
name = "base_layer" #optional name for the layer
keys = """
A
"""

#[[input_device.joystick]]
#name = "default"
#pin_x = "GPIO18"
#pin_y = "GPIO17"
#pin_z = "_"
#transform = [[1, 0], [0, 1]]
#bias = [0, 0]
#resolution = 1

[ble]
enabled = true

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false
