# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "ryttge"
chip = "esp32s3"
usb_enable = true

[matrix]
# Row and col pins are mandatory
row_pins = ["GPIO6"]
col_pins = ["GPIO7"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 1
cols = 1
layers = 1
keymap = [
    [
        ["A",],
    ],
]

[[input_device.joystick]]
name = "default"
pin_x = "GPIO18"
pin_y = "GPIO17"
pin_z = "_"
transform = [[1, 0], [0, 1]]
bias = [0, 0]
resolution = 1

[ble]
enabled = true

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false
